import Providers from '@/components/layout/Providers';
import Navbar from '../components/layout/Navbar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='container mx-auto'>
        <Providers>
          <section className='nav'>
            <Navbar />
          </section>
          <section className='main mt-20 sm:mt-5'>{children}</section>
        </Providers>
      </body>
    </html>
  );
}
